### ISSUE TITLE
Wrapper feature selection for multi-class and continuous variables?

### ISSUE THREAD

**Issue by hanamthang** [JingweiToo/Wrapper-Feature-Selection-Toolbox-Python#1]
Hi there, 

Thank you for your hard works on Python version of the wrapper feature selection. As I understood, all the codes are for binary problems. You said we can use these codes adapting to multi-class and/or continuous variables but need to rewrite all functions. 

So, will you release another version of this kind of wrapper feature selection for multi-class and/or continuous variables in the future? We used the Genetic Algorithm and PSO previously, and loving to extend the experiments to other metaheuristic algorithms. 

To the best,
Thang

**Comment by JingweiToo** [comment]
Hi,

The demonstrations provided are binary problems. However, these tools are also applicable to the multiclass problem too.

**Comment by hanamthang** [comment]
Hi JingweiToo,

I just tested your codes with data for multiclasses (4 classes) problems and it worked quite smoothly. Do we need to change something in the codes of HHO.py (for example) to completely adapt to multiclasses problems?

Many thanks,
Thang

**Comment by JingweiToo** [comment]
Hi,

I think nothing to change for multi-class because I am using the sklearn toolkit for the fitness function

**Comment by hanamthang** [comment]
All clear. 

Many thanks.
Thang
