### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Iqra-Yousaf** [JingweiToo/Wrapper-Feature-Selection-Toolbox-Python#11]
parameter

IndexErrorTraceback (most recent call last)
<ipython-input-63-3408fd7535cc> in <module>()
      1 
      2 print("parameter")
----> 3 jfs(xtrain, ytrain, opts)

C:\Users\karkorum computer\FS\FS\hho.pyc in jfs(xtrain, ytrain, opts)
     59     # Parameters
     60     ub    = 1
---> 61     lb    = 0
     62     thres = 0.5
     63     beta  = 1.5    # levy component

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by JingweiToo** [comment]
Please specify the issue more clearly. Is that your dataset similar structure to the example?

**Comment by Iqra-Yousaf** [comment]
Hello sir, i did not check your mail. I am working on bug severity
prediction with textual datset. I am using Convolutional neural network
model. I want to use HHO for optimizing hyperparameter of CNN. can you
guide me how to use hho for optimizing hyperparameters.
