### ISSUE TITLE
solution please

### ISSUE THREAD

**Issue by Mohammedsaied89** [JingweiToo/Wrapper-Feature-Selection-Toolbox-Python#12]
when i put in spyder 
from FS.pso import jfs 
message appear to me ( No module named 'FS' )

**Comment by JingweiToo** [comment]
Make sure the FS folder is in the same folder as your Main script.

**Comment by Mohammedsaied89** [comment]
Which FS folder ?

**Comment by JingweiToo** [comment]
The folder or place where you run your program. Let say your Main script is Folder A, then make sure the FS folder is inside folder A

**Comment by Mohammedsaied89** [comment]
I didn't find FS folder
Where I can find it

**Comment by Mohammedsaied89** [comment]
ok i got it thank you
