### ISSUE TITLE
regression problem

### ISSUE THREAD

**Issue by Mohammedsaied89** [JingweiToo/Wrapper-Feature-Selection-Toolbox-Python#13]
when i changed knn with linear regression and changed accuracy with r2 and mean squared error 
i got this error ( ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.)
my dataset consist of 5 input and 1 output and all numerical

**Comment by JingweiToo** [comment]
I think it is your dataset issue. Your label might be seriously imbalanced. Change the stratified holdout to normal holdout.
