### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Najme-naseri** [JingweiToo/Wrapper-Feature-Selection-Toolbox-Python#14]
Hello dear Jingwei Too.
I am a graduate student of data science. And I used your code to implement my dissertation.
I want to know if you have determined the parameters of the algorithms based on the articles?
Thank you in advance for your response.
najmenaseri20@gmail.com

**Comment by JingweiToo** [comment]
Hi,

Basically, I will set the default parameters based on the articles.
However, You may also refer to those related articles for parameter settings

Best Regards,
Jingwei Too

**Comment by Najme-naseri** [comment]
Hi
Thank you very much for answering my question.
If possible, can you tell me about the articles you have used because I
need to refer to them?
Thank you in advance for your response.

‫‪Jingwei Too‬‏ ***@***.***‬‏> در تاریخ سه‌شنبه ۷ دسامبر
۲۰۲۱ ساعت ۱۵:۴۶ نوشت:‬

**Comment by JingweiToo** [comment]
Hi,

You may search the related articles on google scholar and set the
parameters. I am sorry because I am busy and I have no time to search for
those articles for you.



Best Regards,
Jingwei Too

**Comment by Najme-naseri** [comment]
Sure، thank you.
