### ISSUE TITLE
Binary Conversion

### ISSUE THREAD

**Issue by mpriyadh** [JingweiToo/Wrapper-Feature-Selection-Toolbox-Python#15]
Hi JingweiToo
First I want to really congratulate and thank you for this great contribution.
Can you please elaborate about the significance and need for this binary conversion function in the HHO.py module
Thanks in advance..

**Comment by JingweiToo** [comment]
Hi, 

It is used to convert the continuous solution into a binary version (which is only 0 or 1).

**Comment by mpriyadh** [comment]
yes I understood that point. Can you please tell me the need to convert to binary? can we not proceed without converting

**Comment by JingweiToo** [comment]
Because the solution is presenting continuously while we are going to detect only feature is selected (1) or feature is not selected (0).
