### ISSUE TITLE
To change fitness with XGBoot or Random forest?

### ISSUE THREAD

**Issue by rPromptt** [JingweiToo/Wrapper-Feature-Selection-Toolbox-Python#6]
Hello Jing Wei,
Thank you for the hard work, could you please advise how to implement your wrapper with a different fitness function such as the XGBoost or Random forest. I can see there're quite a lot of code steps in the folder named functionHO.py and I don't want to mess things up?

Best Regards,
rpr.

**Comment by JingweiToo** [comment]
Change code in the fitness function file
