### ISSUE TITLE
Using selected features with other Neural Network models like LSTM

### ISSUE THREAD

**Issue by erendeliaslan** [JingweiToo/Wrapper-Feature-Selection-Toolbox-Python#7]
Hello Jing Wei. I have to say that was an amazing content for feature selection and maybe the best. I just want to ask you I am trying to make an hybridmodel with PSO and LSTM. I think your algorithm suits well. What do you think? Is itpossible to find features with using PSO (with the error that calculated by K-NN) and model with selected features by using LSTM.

**Comment by JingweiToo** [comment]
Possible, please refer to research articles.
